/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange username + password for an access/refresh pair.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new pair (rotates the refresh).
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the supplied refresh token. Idempotent.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bots */
        get: operations["list_bots_api_bots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}/hot-reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hot Reload
         * @description Reload a bot's rule files. Requires ``bot_admin`` or higher.
         *
         *     Hot-reload swaps the live classifier + DSL dispatcher, so it
         *     materially changes the bot's behaviour for every user. Read-only
         *     callers (``readonly`` role) can still see hits via ``/ws/rules/hits``
         *     but cannot trigger a reload.
         */
        post: operations["hot_reload_api_bots__bot_id__hot_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Return events from one or all visible bots' ring buffers.
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{bot_id}/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__bot_id___event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{bot_id}/{event_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Event
         * @description Re-dispatch a buffered event through the router in dry-run mode.
         *
         *     Only dry-run is supported (``dry_run=True``). Actual re-sending to an
         *     adapter would bypass rate-limits and idempotency — we refuse.
         */
        post: operations["replay_event_api_events__bot_id___event_id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Namespaces */
        get: operations["list_namespaces_api_kv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kv/{scope}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_api_kv__scope___file__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kv/{scope}/{file}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank */
        get: operations["rank_api_kv__scope___file__rank_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kv/{scope}/{file}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Key */
        get: operations["read_key_api_kv__scope___file___key__get"];
        put?: never;
        post?: never;
        /** Delete Key */
        delete: operations["delete_key_api_kv__scope___file___key__delete"];
        options?: never;
        head?: never;
        /** Write Key */
        patch: operations["write_key_api_kv__scope___file___key__patch"];
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{name}/hits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hits For
         * @description Return recent hits for a given handler name.
         *
         *     Time is emitted as ISO-8601 (UTC) to match ``/api/audit`` and
         *     ``/api/events``; the UI should not have to switch formatters per
         *     endpoint.
         */
        get: operations["hits_for_api_rules__name__hits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rule Files */
        get: operations["list_rule_files_api_rules_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Rule File */
        get: operations["read_rule_file_api_rules_files_content_get"];
        /**
         * Save Rule File
         * @description Save a ``.ling`` file. Requires ``bot_admin`` — saves can hot-reload
         *     the live router which would otherwise let any read-only viewer
         *     rewrite handler logic.
         */
        put: operations["save_rule_file_api_rules_files_content_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/lint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lint Rule Source
         * @description Lint a raw ``.ling`` snippet; does not touch disk.
         *
         *     We accept the raw content (rather than a bot/path pair) so the
         *     editor can live-lint without each keystroke requiring a file save.
         *     No bot visibility check because no data crosses tenant boundaries.
         */
        post: operations["lint_rule_source_api_rules_lint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_api_agents__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{name}/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Triggers
         * @description Return the agent's bot's matchable DSL triggers for the inline-suggest panel.
         *
         *     Cheap to call: a provider closure walks the live classifier each
         *     time so hot-reload reflects on the very next poll. When the agent
         *     isn't backed by a bot (test harness, agent-only deployments) we
         *     return an empty list — the composer panel hides itself in that case.
         *
         *     Reused across both panels: the chat composer's autocomplete and any
         *     future ``/help`` mirror in the SPA. RBAC: same as ``/api/agents`` —
         *     visible to every authenticated role; triggers don't reveal anything
         *     a user couldn't discover by typing.
         */
        get: operations["list_triggers_api_agents__name__triggers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{name}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory
         * @description Return the agent memory snapshot for ``(user_id, scope_id)``.
         *
         *     Bootstrapped bots provide a KV-backed snapshot with short-term history,
         *     running summary and the user's profile. Minimal test harnesses and
         *     standalone agent registries may still expose the legacy in-memory
         *     ``runtime.memory`` shape, so we keep that as a compatibility fallback.
         */
        get: operations["memory_api_agents__name__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{name}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Single-shot chat. Routes through the DSL classifier first.
         *
         *     Mirrors ``/ws/agents/{name}/stream``: when ``attach_bot_to_webui``
         *     has installed a web chat dispatcher for this agent, we delegate
         *     so triggers like ``我的灵玉`` reach their ``.ling`` handler. Without
         *     a dispatcher (e.g. minimal test harness) we fall back to a direct
         *     ``runtime.invoke`` like before.
         */
        post: operations["chat_api_agents__name__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_audit_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return a redacted view of the webui config.
         *
         *     Secret-looking keys (api_key, token, jwt_secret, password, …) are
         *     replaced with ``***`` so the UI can render settings without leaking
         *     secrets to the browser console.
         */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/assets/{rel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bot Asset
         * @description Stream an image from the bot's ``assets/`` tree.
         *
         *     Sample request: ``GET /api/files/assets/picture/思思.jpg`` →
         *     ``<bot_base_dir>/assets/picture/思思.jpg``.
         *
         *     The asset root is plumbed via :func:`set_asset_root` (called by
         *     ``attach_bot_to_webui``). Without a root configured we return 404
         *     rather than guessing — same as a missing file.
         */
        get: operations["get_bot_asset_api_files_assets__rel__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy Remote Image
         * @description Stream a remote image through the WebUI so strict CSP can serve it.
         *
         *     DSL rules emit lots of ``±img=https://...±`` URLs (108 distinct
         *     hosts in the migrated ``dicpro.txt``). With ``img-src 'self'`` —
         *     the WebUI's default CSP — the browser refuses to render any of
         *     them. Rather than relax CSP we route them through here:
         *
         *     * fetch over ``http(s)`` only (other schemes are rejected),
         *     * cap the response size and time,
         *     * verify the upstream ``Content-Type`` is an image, and
         *     * strip credentials / cookies, never follow more than a few redirects.
         *
         *     On any failure we return 502 with no body — the client just sees
         *     a broken ``<img>`` placeholder, which is the same UX as a remote
         *     host being temporarily down.
         */
        get: operations["proxy_remote_image_api_files_proxy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSummary */
        AgentSummary: {
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /**
             * Token Today
             * @default 0
             */
            token_today: number;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: string;
            /** Time */
            time: string;
            /** Bot Id */
            bot_id: string;
            /** User Id */
            user_id: string;
            /** Scope Id */
            scope_id: string;
            /** Kind */
            kind: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "err";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** BotStatus */
        BotStatus: {
            /** Id */
            id: string;
            /**
             * Platform
             * @default unknown
             */
            platform: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Online
             * @default false
             */
            online: boolean;
            /** Last Event At */
            last_event_at?: number | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Input */
            input: string;
            /** History Key */
            history_key?: string | null;
            /** Scope Id */
            scope_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Content */
            content: string;
            /**
             * Tool Calls Made
             * @default 0
             */
            tool_calls_made: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Source
             * @default agent
             */
            source: string;
            /**
             * Segments
             * @default []
             */
            segments: components["schemas"]["ChatSegment"][];
        };
        /**
         * ChatSegment
         * @description One piece of a rich chat reply (text or image).
         *
         *     Mirrors the WS frame shape so the SPA can use the same renderer
         *     on both transports.
         */
        ChatSegment: {
            /** Kind */
            kind: string;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Alt
             * @default
             */
            alt: string;
            /**
             * Delay Before S
             * @default 0
             */
            delay_before_s: number;
        };
        /**
         * EventEnvelope
         * @description Slimmed event view sent to the browser.
         *
         *     Avoids returning the raw adapter payload (may contain secrets). The
         *     full pydantic Event is not exposed; adapters own `.raw`.
         */
        EventEnvelope: {
            /** Seq */
            seq: number;
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Bot Id */
            bot_id: string;
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
            /** Sender */
            sender: {
                [key: string]: unknown;
            };
            /** Time */
            time: string;
            /** Kind */
            kind: string;
            /** Segments */
            segments: {
                [key: string]: unknown;
            }[];
            /** Text */
            text: string;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventEnvelope"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Time */
            time: string;
            /** Bots */
            bots: components["schemas"]["BotStatus"][];
        };
        /**
         * HotReloadResponse
         * @description Result of ``POST /api/bots/{bot_id}/hot-reload``.
         *
         *     Mirrors :class:`linling_cli.bootstrap.ReloadReport` plus the
         *     ``reloaded`` count for backward compat with the older callback
         *     interface that returned ``{"reloaded": int, "errors": [...]}``.
         */
        HotReloadResponse: {
            /**
             * Reloaded
             * @default 0
             */
            reloaded: number;
            /**
             * Files
             * @default 0
             */
            files: number;
            /**
             * Applied
             * @default true
             */
            applied: boolean;
            /** Errors */
            errors?: string[];
        };
        /** KvNamespace */
        KvNamespace: {
            /** Scope */
            scope: string;
            /** File */
            file: string;
            /** Count */
            count: number;
        };
        /** KvPage */
        KvPage: {
            /** Items */
            items: components["schemas"]["KvRow"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** KvRankResponse */
        KvRankResponse: {
            /** Rows */
            rows: components["schemas"]["KvRankRow"][];
            /** Formatted */
            formatted: string;
        };
        /** KvRankRow */
        KvRankRow: {
            /** Rank */
            rank: number;
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Numeric */
            numeric: number;
        };
        /** KvRow */
        KvRow: {
            /** Bot Id */
            bot_id: string;
            /** Scope */
            scope: string;
            /** File */
            file: string;
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Updated At */
            updated_at: number;
        };
        /** KvWriteRequest */
        KvWriteRequest: {
            /** Value */
            value: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "superadmin" | "bot_admin" | "readonly";
            /** Bots */
            bots: string[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh */
            refresh: string;
        };
        /**
         * RuleFile
         * @description Metadata entry for one ``.ling`` rule file.
         */
        RuleFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /**
             * Handler Count
             * @default 0
             */
            handler_count: number;
        };
        /**
         * RuleFileContent
         * @description Full content of one rule file.
         */
        RuleFileContent: {
            /** Path */
            path: string;
            /** Content */
            content: string;
        };
        /**
         * RuleFileSaveRequest
         * @description Body for updating a rule file.
         */
        RuleFileSaveRequest: {
            /** Content */
            content: string;
            /**
             * Reload
             * @default true
             */
            reload: boolean;
            /**
             * Lint First
             * @default true
             */
            lint_first: boolean;
        };
        /**
         * RuleFileSaveResult
         * @description Response from a save+reload cycle.
         */
        RuleFileSaveResult: {
            /** Saved */
            saved: boolean;
            /** Issues */
            issues?: components["schemas"]["RuleLintIssue"][];
            /**
             * Reloaded
             * @default false
             */
            reloaded: boolean;
            /**
             * Handlers
             * @default 0
             */
            handlers: number;
        };
        /**
         * RuleLintIssue
         * @description One lint finding.
         */
        RuleLintIssue: {
            /** Line */
            line: number;
            /**
             * Col
             * @default 0
             */
            col: number;
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Message */
            message: string;
        };
        /**
         * RuleLintResult
         * @description Response from linting a snippet.
         */
        RuleLintResult: {
            /** Issues */
            issues?: components["schemas"]["RuleLintIssue"][];
            /**
             * Handler Count
             * @default 0
             */
            handler_count: number;
        };
        /** RuleSummary */
        RuleSummary: {
            /** Name */
            name: string;
            /** Trigger */
            trigger: string;
            /**
             * Hits Today
             * @default 0
             */
            hits_today: number;
            /**
             * Avg Latency Ms
             * @default 0
             */
            avg_latency_ms: number;
            /** Last Error */
            last_error?: string | null;
        };
        /**
         * SettingsResponse
         * @description Redacted config snapshot.
         *
         *     The structure mirrors :class:`WebUIConfig` but secret-looking
         *     fields are replaced with ``"***"``. The shape is intentionally open
         *     (``extra="allow"``) so config additions ship without breaking the
         *     OpenAPI contract; the UI dereferences known keys defensively.
         */
        SettingsResponse: {
            /**
             * Role
             * @description Authenticated caller's role.
             */
            role: string;
        } & {
            [key: string]: unknown;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
            /** Access Expires At */
            access_expires_at: number;
            /** Refresh Expires At */
            refresh_expires_at: number;
        };
        /**
         * TriggerSuggestion
         * @description One DSL trigger surfaced to the chat composer's inline-suggest panel.
         *
         *     The frontend uses ``label`` for display, ``literal_prefix`` for the
         *     pre-fill on click (so triggers with regex placeholders like ``(.*)``
         *     don't paste a still-not-matchable shape into the input), and
         *     ``has_args`` to decide whether a click should auto-send or just
         *     park the cursor at the placeholder.
         */
        TriggerSuggestion: {
            /** Raw */
            raw: string;
            /** Label */
            label: string;
            /**
             * Has Args
             * @default false
             */
            has_args: boolean;
            /**
             * Literal Prefix
             * @default
             */
            literal_prefix: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** _MemoryView */
        _MemoryView: {
            /** Short Term */
            short_term: {
                [key: string]: unknown;
            }[];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Long Term
             * @default []
             */
            long_term: {
                [key: string]: unknown;
            }[];
        };
        /** _ReplayRequest */
        _ReplayRequest: {
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /** _ReplayResponse */
        _ReplayResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Refresh token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bots_api_bots_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hot_reload_api_bots__bot_id__hot_reload_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotReloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                bot_id?: string | null;
                since_seq?: number | null;
                limit?: number;
                kind?: string | null;
                scope_kind?: string | null;
                mine?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__bot_id___event_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bot_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_event_api_events__bot_id___event_id__replay_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bot_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ReplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_ReplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_namespaces_api_kv_get: {
        parameters: {
            query?: {
                bot_id?: string | null;
                scope?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvNamespace"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_kv__scope___file__get: {
        parameters: {
            query?: {
                bot_id?: string | null;
                prefix?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                scope: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_api_kv__scope___file__rank_get: {
        parameters: {
            query?: {
                bot_id?: string | null;
                order?: string;
                top?: number;
                sep?: string;
                fmt?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                scope: string;
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvRankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_key_api_kv__scope___file___key__get: {
        parameters: {
            query?: {
                bot_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                scope: string;
                file: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_api_kv__scope___file___key__delete: {
        parameters: {
            query?: {
                bot_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                scope: string;
                file: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_key_api_kv__scope___file___key__patch: {
        parameters: {
            query?: {
                bot_id?: string | null;
            };
            header?: {
                "If-Match"?: string | null;
                authorization?: string | null;
            };
            path: {
                scope: string;
                file: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KvWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KvRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hits_for_api_rules__name__hits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rule_files_api_rules_files_get: {
        parameters: {
            query: {
                bot_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_rule_file_api_rules_files_content_get: {
        parameters: {
            query: {
                bot_id: string;
                /** @description Bot-relative file path */
                path: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleFileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_rule_file_api_rules_files_content_put: {
        parameters: {
            query: {
                bot_id: string;
                path: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleFileSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleFileSaveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lint_rule_source_api_rules_lint_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleLintResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_agents__name__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_triggers_api_agents__name__triggers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_api_agents__name__memory_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                scope_id?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_MemoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_agents__name__chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_audit_get: {
        parameters: {
            query?: {
                bot_id?: string | null;
                user_id?: string | null;
                kind?: string | null;
                outcome?: string | null;
                since?: number | null;
                until?: number | null;
                q?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_audit_csv_get: {
        parameters: {
            query?: {
                bot_id?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export of audit rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bot_asset_api_files_assets__rel__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rel: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_remote_image_api_files_proxy_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
